name: Node.js CI Build/Test

on:
  pull_request:
    branches: [ dev, main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      -
        name: Install Dependencies
        run: npm ci --legacy-peer-deps
      -
        name: Create .env file
        run: |
          touch .env
          echo '
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            ACCESS_KEY_ID=${{ secrets.ACCESS_KEY_ID }}
            SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }}
            REGION=${{ secrets.REGION }}
          ' >> .env
      -
        name: Bundle
        run: npm run build
      -
        name: Run Test Suite
        run: npm test
